version: "3.6"

services:
  db:
    image: postgis/postgis:14-master
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monpsysante
      POSTGRES_USER: monpsysante
      POSTGRES_PASSWORD: monpsysante
    restart: always

volumes:
  db_data:
