version: "3.6"

services:
  db:
    image: postgis/postgis:14-master
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monpsysante
      POSTGRES_USER: monpsysante
      POSTGRES_PASSWORD: monpsysante
    restart: always

  keycloak:
    depends_on:
      - db
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_USER: monpsysante
      DB_PASSWORD: monpsysante
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - start-dev

volumes:
  db_data:
