apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: mon-psy-sante
  name: reporting-expert-weekly
  labels:
    app: mon-psy
spec:
  schedule: "0 6 * * 2"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mon-psy
              image: {{ .Values.global.registry }}/{{ .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}
              envFrom:
                - secretRef:
                    name: app-sealed-secret
                - secretRef:
                    name: pg-user
              command:
                - yarn
                - run
                - cron:launch
                - reportingExpertWeekly
          restartPolicy: Never
