apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: mon-psy-sante
  name: verif-dossiers-ds
  labels:
    app: mon-psy
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mon-psy
              image: {{ .Values.global.registry }}/{{ .Values.global.imageProject }}/{{ .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}
              envFrom:
                - secretRef:
                    name: app-sealed-secret
                - secretRef:
                    name: pg-user
              command:
                - yarn
                - run
                - cron:launch
                - verifFolders
          restartPolicy: Never
