app:
  ~needs: [build-app, seed]

jobs:
  runs:
    seed:
      ~needs: [build-app, pg]
      checkout: false # no need to checkout the repo as we use the docker image
      shell: sh
      image: "{{ .Values.global.registry }}{{ if .Values.global.imageProject }}{{ print `/` .Values.global.imageProject }}{{ end }}/{{ .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}"
      run: "yarn db:init"
      envFrom:
        - secretRef:
            name: pg-app
