apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: mon-psy-sante-preprod
  name: import-data
  labels:
    app: mon-psy
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mon-psy
            image: ghcr.io/socialgouv/mon-psy-sante/app:latest
            envFrom:
            - secretRef:
                name: app-sealed-secret
            - secretRef:
                name: azure-pg-user
            command:
              - yarn
              - run
              - cron:launch
              - importData
          restartPolicy: Never