# This is test of the workflow
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: mon-psy-sante-preprod
  name: send-mail-to-raph
  labels:
    app: mon-psy
spec:
  # Every 10 minutes (test purpose)
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mon-psy
              image: ghcr.io/socialgouv/mon-psy-sante/app:{{ .Values.global.imageTag }}
              envFrom:
                - secretRef:
                    name: app-sealed-secret
                - secretRef:
                    name: pg-user
              command:
                - yarn
                - run
                - cron:launch
                - sendMailToRaph
          restartPolicy: Never
          concurrencyPolicy: Forbid
