app:
  host: monpsy.sante.gouv.fr
  redirectFrom:
    - www.monpsy.sante.gouv.fr
  replicas: 2
  resources:
    limits:
      cpu: 1
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 256Mi

keycloak:
  ingress:
    annotations:
      cert-manager.io: cluster-issuer
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: 'true'
    tls:
      - hosts:
          - "keycloak-{{ .Values.global.host }}"
        secretName: keycloak-crt
