app:
  needs: [seed]

jobs:
  runs:
    db:
      use: SocialGouv/kube-workflow/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
    seed:
      checkout: false # no need to checkout the repo as we use the docker image
      needs: [db]
      shell: sh
      image: "{{ .Values.global.registry }}/{{ .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}"
      run: "yarn db:init"
      envFrom:
        - secretRef:
            name: "pg-user-{{ .Values.global.branchSlug }}"

    db-keycloak:
      use: SocialGouv/kube-workflow/jobs/create-db
      with:
        pgAdminSecretRefName: azure-pg-admin-user
        pgSecretName: "keycloak-db-{{ .Values.global.branchSlug32 }}"
        database: "keycloak_{{ .Values.global.branchSlug32 }}"
        pgUser: "keycloak_{{ .Values.global.branchSlug32 }}"

keycloak:
  extraEnvFrom: |
    - secretRef:
        name: app-sealed-secret
    - secretRef:
        name: "keycloak-db-{{ .Values.global.branchSlug32 }}"
    - secretRef:
        name: keycloak-secrets
