apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak-secrets
spec:
  encryptedData:
    KEYCLOAK_USER: AgBngJRb7ztp+XJNqPCOepXANnpaAc/gc4GnbxG21OwZj6AJO6HW7qyHoraJmQAvfrWTm82Qdw/XCOwQklyL4T1Dw0xU1RjqdLDTWK4HmWo+WotToHdM0K6fygjaNmtb3fHuAW47hqawdxfhj78bqFVvYLsEBbcg9SBZmd42C8DZRlmF3BjXc3gz+SeuiflNjDi72EzqwwyNqDWdrEhLUvQQYXRlWKfkTApoZn4n3pjUZoGuLOiigsIbB5WwtHHv7+pAeNYfjmyxbMDe53TzByowI3Phmf9+SOh7wwPZ8XGz9XjjKxGk5v2/owk8mKzfRmN5DwUQrvq9kkFBO1mLTpG6Dl+obvopl4Ec4fZKM+z2JG1y217j6CqqM+N2/DRGSi5I4Wk6z29pKIycSyx2oyat4RWIQ5IA6OI1P91HQwA3Ui/Dn0+lEEZ4bwTFnHj+GEIJLdmgsrHV1+WuH+YgTNf4BfFtvVIOnVJV4/3KhacwXsYqc3Ar2a2Sx/MLMY+yvn+/jde9AMaEbbZI00FTRllZ6GYOPFJr1jDqmNNhqKIBEpz1EFNfIrNlPuLdgHpOjEGnti2Y3Z+AzJH0wNeLK/72cgGkSxM3o3NqnTn2aPzVcjffECc8GsB+PzXy066NjeEtdRjeYq8ZurAOc96kEPXg3kZ1VnB1fdrAvm8B8lLnumTxizzoyIJdrXXIGfEIUFe6ULbWJg==
    KEYCLOAK_PASSWORD: AgCaDALGwQh5++xySbFupFtyptly0YSy/MbIVRTJtkiuicc8xQFF9kwY5H12OuJ06tzsG9xb+qz/x0OBAZMlDIyH1HWsAGOwSldBbu+g0gM9xGd8Qx4j7So+/YrmhI1AdFO25GvA6M7i/4qVi9P4uUpZAtlRVA0wbyzXj4bfzpI2JEjBPTXT/pY+CtohRIfN6FfWKNWb86IT+LjieTW/8F2o184qSx3xW82Nh1TkemIwhIoOLso+oKST5jq+Vcw87BAofsQnFCaeCf4jXir342T1a3JV8tU6eNbU1Ze3R0Rf2V8orqLUSCyc+j6H9YOlKRGoGRuECQ69/RYARVXY89gyxRATqTHb59sm+3uRR462/jdDmcXayhy/98SjN1MmazxUSCxXbsHIrTbYWXe9Trdx2volge+8lxMIN/wM2PubzuVYo72Zsg+knExYUnNm8fTV+ndfwksuh+zA3asQkxuoVBzviB1E9Sqxr6MadRNil0kMBdVmd5IgJ05mhY1Mm9bBRHlOoh86ZX+oKSTW2QGREyFdLR4ubhW1z5gPC/Sh+wUQ1DWu+6iw5c47YvO5CJfRhDWcYgj7iiOQL1PTKG6Vf/lwsqbTORLzxRJ5I/T5DGzibcesSNv9190i5ZnubiHrTc8dFUCMbc2x+ELduwQgeL66yY+ZBfpA3V28RfvnKHwi2LF3SSn0wgUukI9E1DgCgjY6jl8aX4lDEYfHPXvF7L6t4DvXJDRPyfo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: keycloak-secrets
    type: Opaque
