apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: mon-psy-sante-preprod
  name: send-reporting
  labels:
    app: mon-psy
spec:
  schedule: "0 9 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mon-psy
              image: ghcr.io/socialgouv/mon-psy-sante/app:{{ .Values.global.imageTag }}
              envFrom:
                - secretRef:
                    name: app-sealed-secret
                - secretRef:
                    name: pg-user
              command:
                - yarn
                - run
                - cron:launch
                - sendReporting
          restartPolicy: Never
          concurrencyPolicy: Forbid
