name: CI

on:
  - push

jobs:
  Build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-master
        env:
          POSTGRES_DB: monpsysante
          POSTGRES_USER: monpsysante
          POSTGRES_PASSWORD: monpsysante
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Installing
        run: yarn --frozen-lockfile

      - name: Env file
        run: cp .env.test .env

      - name: Installing DB
        run: npm run db:init

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run dev&

      - name: Unit test
        run: npm run test

      - name: API test
        run: npm run test:api

      - name: E2E test
        run: npm run cy:run
