name: Preproduction

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: preproduction

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGES
  ##############################################################################
  register:
    name: Build & Register
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Application
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/app
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: preprod

  ##############################################################################
  ## DEPLOY APPLICATION OVER KUBERNETES
  ##############################################################################
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [ register ]
    environment:
      name: preproduction
      url: https://mon-psy-sante-preprod.dev.fabrique.social.gouv.fr
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/autodevops-manifests@v1
        with:
          environment: "preprod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "preprod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
