name: Production

on:
  workflow_dispatch:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGE
  ##############################################################################
  register:
    name: Build & Register docker images
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Application
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imageName: ${{ env.project }}/app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            PRODUCTION=true

  ##############################################################################
  ## DEPLOY PRODUCTION APPLICATION
  ##############################################################################
  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [ register ]
    environment:
      name: production
      url: https://monsoutienpsy.sante.gouv.fr
    steps:
      - uses: SocialGouv/kube-workflow@master
        with:
          environment: prod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
